version: '2'
services:
    ghostceet-app:
        image: ghostceet
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ghostceet-mysql:3306/ghostceet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ghostceet-mysql:
        extends:
            file: mysql.yml
            service: ghostceet-mysql
